name: "Teste de Action"
on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

jobs:
    test-action-job:
        permissions: 
            issues: write
            pull-requests: write
        runs-on: ubuntu:latest
        name: Execução de Custom Action (Docker)
        steps:
            - name: Adicionando Comentário
              uses: ventocilla/action-docker@main
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
                issue-id: ${{ github.event.issue.number }} 
                comment: "Teste de comentário docker"
                GITHUB_REPOSITORY: ${{ github.repository }}